### ISSUE TITLE
buildPlugin.ps1 will sometimes block for a very long time

### ISSUE THREAD

**Issue by ForNeVeR** [matkoch/resharper-sampleplugin#1]
When trying to build my plugin (originating from this template) on Windows, I got the following issue.

### Symptoms

(On Windows, having .NET Core 2.1 installed.)

1. Kill all `VBCSCompiler.exe` processes on the system (because they're sometimes cached and then will hide the issue).
2. Invoke `buildPlugin` gradle task.
3. It will report that the MSBuild process has finished (and it actually is), but it will block after that. `powershell.exe` will stay, gradle will not proceed.

### Analysis

When building the plugin, `buildPlugin.ps1` PowerShell script gets called. It uses the `Invoke-Exe` function that has the following line: https://github.com/matkoch/resharper-sampleplugin/blob/9f1282bd25fd1f3df97764faafa065cd1d3508b8/content/settings.ps1#L22

`-Wait` here will block until **all of the descendant process are stopped**, according to [the documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/start-process?view=powershell-6#optional-parameters). And strarting from .NET Core 2.1, MSBuild will run `VBCSCompiler.exe` daemon that generally stays alive for a long time (and it will stay alive after the build process finishes).

So, PowerShell will wait for `VBCSCompiler.exe` daemon to finish, and Gradle will wait for PowerShell, leading to a build pause.

**Comment by matkoch** [comment]
@ForNeVeR may we use `/nodeReuse:false` instead?

**Comment by ForNeVeR** [comment]
But should we? I'm okay with the default MSBuild behavior. So I personally would let it to manage the daemon processes. Do we have any other issues with that?

**Comment by matkoch** [comment]
True, I released 0.4.0  containing this fix along with some others.
