### ISSUE TITLE
Test framework isn't referenced

### ISSUE THREAD

**Issue by auduchinok** [matkoch/resharper-sampleplugin#4]
We only reference the SDK itself at:
https://github.com/matkoch/resharper-sampleplugin/blob/df17cf8a0920bf088df0ee5d0cb0e8222806a24b/content/src/dotnet/ReSharperPlugin.SamplePlugin/ReSharperPlugin.SamplePlugin.Rider.csproj#L18
We could reference R# test framework and have a simple test project.

**Comment by matkoch** [comment]
Would this be enough?

https://github.com/matkoch/resharper-sampleplugin/commit/7850c02314b821b3cf259d5504bb6efc714427fe

**Comment by auduchinok** [comment]
@matkoch Yes, LGTM.
