### ISSUE TITLE
Clean up props and project files

### ISSUE THREAD

**Issue by auduchinok** [matkoch/resharper-sampleplugin#5]
There're couple of things that don't seem to be needed in a generic template, like language version, or that aren't needed anymore AFAIK, like the wave package reference.

Is the following really needed in the template?
https://github.com/matkoch/resharper-sampleplugin/blob/df17cf8a0920bf088df0ee5d0cb0e8222806a24b/content/src/dotnet/Directory.Build.props#L4

The following is not needed AFAIK.
https://github.com/matkoch/resharper-sampleplugin/blob/df17cf8a0920bf088df0ee5d0cb0e8222806a24b/content/src/dotnet/ReSharperPlugin.SamplePlugin/ReSharperPlugin.SamplePlugin.Rider.csproj#L21

What is the following for in SDK package reference?
https://github.com/matkoch/resharper-sampleplugin/blob/df17cf8a0920bf088df0ee5d0cb0e8222806a24b/content/src/dotnet/ReSharperPlugin.SamplePlugin/ReSharperPlugin.SamplePlugin.Rider.csproj#L19

**Comment by matkoch** [comment]
Fixed in https://github.com/matkoch/resharper-sampleplugin/commit/1eced9b0427270d894c98904ecede39fd58e5673 and https://github.com/matkoch/resharper-sampleplugin/commit/74c91c9b4bdffc2ed8f519ef91679775be7894ed
